### PR TITLE
feat: Added dedicated UI for the plugin. User can now interact with t…

### PR DESCRIPTION
**Pull request by srinivas0210**
…he plugin.

### CODE REVIEW

**Review by six7 — CHANGES_REQUESTED** [review]
Thanks for this! Few things:

We'd want to do the mapping from styleName to styleId right after we do `getStyleIdsWithName`. Those ids already contain id and name (we'd only need to change what's part of the data), so we could just iterate over the JSON, find the matching `styleId`.

On another note, this isn't the most performant way to do things: You iterate over all keys supplied by the JSON and then `startPluginWithParameters` again iterates over ALL text layers in the document. I'd rather suggest we change convertToOldStyle so it takes in an array of oldStyles and an array of newStyles (or rather the mapping object) and just tries to see if the current layer matches any of the oldStyles.

Right now the JSON part only works for layers that have styles applied, not for segments of text that have the style applied (we already have this logic, so I suggest we not change convertToOldStyle, but instead just hand over the right styleid.

We should be throwing out any mapping pairs where either one of those styles can't be found (e.g. because the user provided the wrong name)

Also, the plugin should still be able to run in parameter-mode, the `parameters` property in `manifest.json` should not be removed.

**Comment by srinivas0210** [comment]
Hello Jan. Thanks for reviewing and for the comments.

I am new to the figma plugins and api, so I may have missed some points to cover in my last PR. I am updating the PR now with your suggestions. Here are the few things i have made changes to:

Proper mapping between the style names and style Ids. 
Updated  convertOldToNewStyle .
Removed the code which is iterating many times over all the text nodes.
Added Helper functions to the code. 
Well documented my code this time.
Last one, added parameters again in manifest.json. (but i made showUI invisible, if not it is showing an error).
Made UI changes, now UI is looking better than before :grin:.

I am hereby attaching the working video. You can take a look over here: https://drive.google.com/file/d/1LaMbEFzuqnL6KipDbb6ZdhrFebhZuFyQ/view?usp=sharing

Let me know your comments. I look forward to hearing from you soon.

**Comment by srinivas0210** [comment]
Edit:

Added a small logic to map the parameters in `parameter mode`

**Comment by six7** [comment]
This is great, thank you! I'll merge this in and take it from there, will do a couple more optimizations on the UI and then release it. 👍

**Review by six7 — APPROVED** [review]

**Pull request merged**
